# LP_Template_app.py
import streamlit as st
from docx import Document
from pptx import Presentation
import pdfplumber
import openai  # For AI inference
import os

# Set your OpenAI API key (or use environment variable)
# Make sure to set OPENAI_API_KEY in your environment for security
openai.api_key = st.secrets.get("OPENAI_API_KEY", "")

# Function to extract text from DOCX
def extract_text_docx(file):
    doc = Document(file)
    full_text = []
    for para in doc.paragraphs:
        full_text.append(para.text)
    return "\n".join(full_text)

# Function to extract text from PDF
def extract_text_pdf(file):
    full_text = []
    with pdfplumber.open(file) as pdf:
        for page in pdf.pages:
            full_text.append(page.extract_text())
    return "\n".join(full_text)

# Function to extract text from PPTX
def extract_text_pptx(file):
    prs = Presentation(file)
    full_text = []
    for slide in prs.slides:
        for shape in slide.shapes:
            if hasattr(shape, "text"):
                full_text.append(shape.text)
    return "\n".join(full_text)

# Function to call AI to generate lesson plan JSON
def generate_lesson_plan(text_content):
    """
    This uses OpenAI GPT to convert raw student materials text
    into structured JSON matching your lesson plan template.
    """
    prompt = f"""
    You are an expert UK curriculum designer.

    TASK:
    Using the following student-facing materials, generate a JSON 
    containing all placeholders for a 5-day lesson plan.
    
    Placeholders include:
    Class1_LearningObjective, Class1_SuccessCriteria, Class1_Vocabulary, Class1_KeyQuestions,
    Class1_StarterActivity, Class1_MainTeaching, Class1_DifferentiatedActivities, 
    Class1_Plenary, Class1_Reflection, Class1_Homework
    (and similarly for Classes 2–5).

    Output only valid JSON.

    MATERIALS:
    {text_content}
    """

    response = openai.ChatCompletion.create(
        model="gpt-4",
        messages=[{"role":"user", "content": prompt}],
        temperature=0
    )
    # Extract JSON from AI response
    content = response['choices'][0]['message']['content']
    return content

# Function to populate Word template
def populate_template(json_dict):
    template_path = os.path.join("templates", "WLPT.docx")
    if not os.path.exists(template_path):
        st.error("Template WLPT.docx not found in templates folder!")
        return None

    doc = Document(template_path)
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                for key, value in json_dict.items():
                    placeholder = f"{{{{{key}}}}}"
                    if placeholder in cell.text:
                        cell.text = cell.text.replace(placeholder, value)
    output_path = "LessonPlan_Filled.docx"
    doc.save(output_path)
    return output_path

# Streamlit app starts here
def main():
    st.set_page_config(page_title="5-Day AI Lesson Plan Generator", layout="wide")
    st.title("5-Day AI Lesson Plan Generator")
    st.write("""
    Upload your student-facing materials (DOCX, PDF, PPTX). 
    The app will analyze the content and automatically create 
    a complete 5-day lesson plan in your WLPT Word template.
    """)

    uploaded_files = st.file_uploader(
        "Upload materials", type=["docx", "pdf", "pptx"], accept_multiple_files=True
    )

    if uploaded_files:
        all_text = []
        for file in uploaded_files:
            if file.name.endswith(".docx"):
                all_text.append(extract_text_docx(file))
            elif file.name.endswith(".pdf"):
                all_text.append(extract_text_pdf(file))
            elif file.name.endswith(".pptx"):
                all_text.append(extract_text_pptx(file))

        combined_text = "\n".join(all_text)
        st.info("Extracted text from uploaded materials. Sending to AI...")

        try:
            # Generate lesson plan JSON using AI
            json_str = generate_lesson_plan(combined_text)
            json_dict = eval(json_str)  # Convert JSON string to dict (careful: make sure AI returns valid JSON)
            st.success("Lesson plan generated by AI!")

            # Populate Word template
            output_file = populate_template(json_dict)
            if output_file:
                with open(output_file, "rb") as f:
                    st.download_button(
                        label="Download Populated Lesson Plan",
                        data=f,
                        file_name="LessonPlan_Filled.docx",
                        mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
                    )
        except Exception as e:
            st.error(f"Error generating lesson plan: {e}")
    else:
        st.info("Please upload at least one student-facing material file.")

if __name__ == "__main__":
    main()
